import { Input, InputType } from "../../../Atoms";

const Nationalities = [
  { value: "AFGHAN", label: "Afgana" },
  { value: "ALBANIAN", label: "Albanesa" },
  { value: "GERMAN", label: "Alemán" },
  { value: "AMERICAN", label: "Americana" },
  { value: "ANDORRAN", label: "Andorrana" },
  { value: "ANGOLAN", label: "Angoleña" },
  { value: "ANGUILLAN", label: "Anguila" },
  { value: "ANTIGUAN_OR_BARBUDAN", label: "Antiguan o barbudan" },
  { value: "ANTARCTIC", label: "Antártica" },
  { value: "ALGERIAN", label: "Argelina" },
  { value: "ARGENTINE", label: "Argentino" },
  { value: "ARMENIAN", label: "Armenia" },
  { value: "ARUBAN", label: "Aruba" },
  { value: "AUSTRALIAN", label: "Australiana" },
  { value: "AUSTRIAN", label: "Austriaca" },
  { value: "AZERBAIJANI", label: "Azerbaiyana" },
  { value: "BAHAMIAN", label: "Bahameña" },
  { value: "BAHRAINI", label: "Bahreiní" },
  { value: "BANGLADESHI", label: "Bangladesí" },
  { value: "BARBADIAN", label: "Barbadense" },
  { value: "BARTHЕLEMOIS", label: "Barthélemois" },
  { value: "BASOTHO", label: "Basotho" },
  { value: "BELGIAN", label: "Belga" },
  { value: "BELIZEAN", label: "Beliceña" },
  { value: "BENINESE", label: "Beninés" },
  { value: "BERMUDIAN", label: "Bermudeño" },
  { value: "BELARUSIAN", label: "Bielorrusa" },
  { value: "BIOT", label: "Biot" },
  { value: "BURUNDIAN", label: "Birmana" },
  { value: "BISSAU_GUINEAN", label: "Bissau guinean" },
  { value: "BOLIVIAN", label: "Boliviano" },
  { value: "BOSNIAN_AND_HERZEGOVINIAN", label: "Bosnio y herzegoviniano" },
  { value: "BOTSWAN", label: "Botsuana" },
  { value: "BRAZILIAN", label: "Brasileño" },
  { value: "BRITISH", label: "Británico" },
  { value: "BRUNEIAN", label: "Bruneano" },
  { value: "BURKINABE", label: "Burkinés" },
  { value: "BURMESE", label: "Burmese" },
  { value: "BHUTANESE", label: "Bután" },
  { value: "BULGARIAN", label: "Búlgaro" },
  { value: "CAPE_VERDEAN", label: "Caboverdiano" },
  { value: "CAYMANIAN", label: "Caimán" },
  { value: "CAMBODIAN", label: "Camboyana" },
  { value: "CAMEROONIAN", label: "Camerunés" },
  { value: "CANADIAN", label: "Canadiense" },
  { value: "CENTRAL_AFRICAN", label: "Centroafricano" },
  { value: "CHADIAN", label: "Chadiano" },
  { value: "CZECH", label: "Checo" },
  { value: "CHILEAN", label: "Chileno" },
  { value: "CHINESE", label: "Chino" },
  { value: "CYPRIOT", label: "Chipriota" },
  { value: "COLOMBIAN", label: "Colombiano" },
  { value: "COMORIAN", label: "Comorense" },
  { value: "CONGOLESE", label: "Congoleño" },
  { value: "NORTH_KOREAN", label: "Corea del Norte" },
  { value: "COSTA_RICAN", label: "Costa Rica" },
  { value: "CROATIAN", label: "Croata" },
  { value: "CUBAN", label: "Cubano" },
  { value: "DANISH", label: "Danés" },
  { value: "UNKNOWN", label: "Desconocida" },
  { value: "DJIBOUTIAN", label: "Djibouti" },
  { value: "DOMINICAN", label: "Dominicano" },
  { value: "ECUADORIAN", label: "Ecuatoriano" },
  { value: "EGYPTIAN", label: "Egipcio" },
  { value: "EMIRATI", label: "Emiratí" },
  { value: "ERITREAN", label: "Eritreo" },
  { value: "ESTONIAN", label: "Estonio" },
  { value: "ETHIOPIAN", label: "Etíope" },
  { value: "FAROESE", label: "Feroés" },
  { value: "FILIPINO", label: "Filipino" },
  { value: "FINNISH", label: "Finlandés" },
  { value: "FIJIAN", label: "Fiyiano" },
  { value: "FRENCH", label: "Francés" },
  { value: "FRENCH_GUIANESE", label: "French guianese" },
  { value: "GABONESE", label: "Gabonés" },
  { value: "GAMBIAN", label: "Gambiano" },
  { value: "GEORGIAN", label: "Georgiano" },
  { value: "GHANAIAN", label: "Ghanés" },
  { value: "GIBRALTARIAN", label: "Gibraltareño" },
  { value: "GRENADIAN", label: "Granadino" },
  { value: "GREEK", label: "Griego" },
  { value: "GREENLANDIC", label: "Groenlandés" },
  { value: "GUADELOUPE", label: "Guadalupe" },
  { value: "GUAMBAT", label: "Guambat" },
  { value: "GUATEMALAN", label: "Guatemalteco" },
  { value: "EQUATORIAL_GUINEAN", label: "Guinea ecuatorial" },
  { value: "GUINEAN", label: "Guineano" },
  { value: "GUYANESE", label: "Guyanés" },
  { value: "FRENCH_POLYNESIAN", label: "Guyanés francés" },
  { value: "HAITIAN", label: "Haitiano" },
  { value: "DUTCH", label: "Holandés" },
  { value: "HONDURAN", label: "Hondureño" },
  { value: "HONG_KONGESE", label: "Hong kongese" },
  { value: "HUNGARIAN", label: "Húngaro" },
  { value: "INDIAN", label: "Indio" },
  { value: "INDONESIAN", label: "Indonesio" },
  { value: "IRISH", label: "Irlandés" },
  { value: "ICELANDIC", label: "Islandés" },
  {
    value: "HEARD_ISLAND_AND_MCDONALD_ISLANDS",
    label: "Islas escuchadas e islas mcdonald",
  },
  { value: "BOUVET_ISLANDER", label: "Isleño Bouvet" },
  { value: "COOK_ISLANDER", label: "Isleño cocinero" },
  { value: "CHANNEL_ISLANDER", label: "Isleño de canal" },
  { value: "FALKLAND_ISLANDER", label: "Isleño de las Malvinas" },
  { value: "CHRISTMAS_ISLANDER", label: "Isleño de navidad" },
  { value: "COCOS_ISLANDER", label: "Isleño del coco" },
  { value: "US_VIRGIN_ISLANDER", label: "Isleño virgen" },
  { value: "BRITISH_VIRGIN_ISLANDER", label: "Isleño virgen británico" },
  { value: "ITALIAN", label: "Italian" },
  { value: "IVORIAN", label: "Ivorian" },
  { value: "JAMAICAN", label: "Jamaican" },
  { value: "JAPANESE", label: "Japanese" },
  { value: "JORDANIAN", label: "Jordanian" },
  { value: "KAZAKH", label: "Kazakh" },
  { value: "KENYAN", label: "Kenyan" },
  { value: "KITTITIAN_OR_NEVISIAN", label: "Kittitian or nevisian" },
  { value: "KUWAITI", label: "Kuwaiti" },
  { value: "KYRGYZ", label: "Kyrgyz" },
  { value: "LAO", label: "Lao" },
  { value: "LATVIAN", label: "Latvian" },
  { value: "LEBANESE", label: "Lebanese" },
  { value: "LIBERIAN", label: "Liberian" },
  { value: "LIBYAN", label: "Libyan" },
  { value: "LIECHTENSTEINER", label: "Liechtensteiner" },
  { value: "LITHUANIAN", label: "Lithuanian" },
  { value: "LUXEMBOURGISH", label: "Luxembourgish" },
  { value: "MACANESE", label: "Macanese" },
  { value: "MACEDONIAN", label: "Macedonian" },
  { value: "MAHORAN", label: "Mahoran" },
  { value: "MALAGASY", label: "Malagasy" },
  { value: "MALAWIAN", label: "Malawian" },
  { value: "MALAYSIAN", label: "Malaysian" },
  { value: "MALDIVIAN", label: "Maldivian" },
  { value: "MALIAN", label: "Malian" },
  { value: "MALTESE", label: "Maltese" },
  { value: "MANX", label: "Manx" },
  { value: "MARSHALLESE", label: "Marshallese" },
  { value: "MARTINIQUAIS", label: "Martiniquais" },
  { value: "MAURITANIAN", label: "Mauritanian" },
  { value: "MAURITIAN", label: "Mauritian" },
  { value: "MEXICAN", label: "Mexican" },
  { value: "MICRONESIAN", label: "Micronesian" },
  { value: "MOLDOVAN", label: "Moldovan" },
  { value: "MONGOLIAN", label: "Mongolian" },
  { value: "MONTENEGRIN", label: "Montenegrin" },
  { value: "MONTSERRATIAN", label: "Montserratian" },
  { value: "MONEGASQUE", label: "Monégasque" },
  { value: "MOROCCAN", label: "Moroccan" },
  { value: "MOZAMBICAN", label: "Mozambican" },
  { value: "NAMIBIAN", label: "Namibian" },
  { value: "NAURUAN", label: "Nauruan" },
  { value: "NEPALESE", label: "Nepalese" },
  { value: "NETHERLANDS_ANTILLEAN", label: "Netherlands antillean" },
  { value: "NEW_CALEDONIAN", label: "New caledonian" },
  { value: "NEW_ZEALANDER", label: "New zealander" },
  { value: "NI_VANUATU", label: "Ni vanuatu" },
  { value: "NICARAGUAN", label: "Nicaraguan" },
  { value: "NIGERIEN", label: "Nigerien" },
  { value: "NIUEAN", label: "Niuean" },
  { value: "NORFOLK_ISLANDER", label: "Norfolk islander" },
  { value: "NORWEGIAN", label: "Norwegian" },
  { value: "PAKISTANI", label: "Pakistani" },
  { value: "PALAUAN", label: "Palauan" },
  { value: "PANAMANIAN", label: "Panamanian" },
  { value: "PAPUA_NEW_GUINEAN", label: "Papua new guinean" },
  { value: "PARAGUAYAN", label: "Paraguayan" },
  { value: "PERUVIAN", label: "Peruvian" },
  { value: "PITCAIRN_ISLANDER", label: "Pitcairn islander" },
  { value: "POLISH", label: "Polish" },
  { value: "PORTUGUESE", label: "Portuguese" },
  { value: "PUERTO_RICAN", label: "Puerto rican" },
  { value: "QATARI", label: "Qatari" },
  { value: "REUNIONNAIS", label: "Reunionnais" },
  { value: "ROMANIAN", label: "Romanian" },
  { value: "RUSSIAN", label: "Russian" },
  { value: "RWANDAN", label: "Rwandan" },
  { value: "SAHRAWIAN", label: "Sahrawian" },
  { value: "SAINT_HELENIAN", label: "Saint helenian" },
  { value: "SAINT_LUCIAN", label: "Saint lucian" },
  { value: "SAINT_MARTINOISE", label: "Saint martinoise" },
  {
    value: "SAINT_PIERRAIS_OR_MIQUELONNAIS",
    label: "Saint pierrais or miquelonnais",
  },
  { value: "SALVADORAN", label: "Salvadoran" },
  { value: "SAMMARINESE", label: "Sammarinese" },
  { value: "AMERICAN_SAMOAN", label: "Samoa Americana" },
  { value: "SAMOAN", label: "Samoan" },
  { value: "SAO_TOMEAN", label: "Sao tomean" },
  { value: "SAUDI", label: "Saudi" },
  { value: "SENEGALESE", label: "Senegalese" },
  { value: "SERBIAN", label: "Serbian" },
  { value: "SEYCHELLOIS", label: "Seychellois" },
  { value: "SIERRA_LEONEAN", label: "Sierra leonean" },
  { value: "SINGAPOREAN", label: "Singaporean" },
  { value: "SLOVAKIAN", label: "Slovakian" },
  { value: "SLOVENIAN", label: "Slovenian" },
  { value: "SOLOMON_ISLANDER", label: "Solomon islander" },
  { value: "SOMALIAN", label: "Somalian" },
  { value: "SOUTH_AFRICAN", label: "South african" },
  {
    value: "SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDER",
    label: "South georgia and the south sandwich islander",
  },
  { value: "SOUTH_KOREAN", label: "South korean" },
  { value: "SPANISH", label: "Spanish" },
  { value: "SRI_LANKAN", label: "Sri lankan" },
  { value: "SUDANESE", label: "Sudanese" },
  { value: "SURINAMESE", label: "Surinamese" },
  { value: "SVALBARD", label: "Svalbard" },
  { value: "SWAZI", label: "Swazi" },
  { value: "SWEDISH", label: "Swedish" },
  { value: "SWISS", label: "Swiss" },
  { value: "SYRIAN", label: "Syrian" },
  { value: "TAIWANESE", label: "Taiwanese" },
  { value: "TAJIKISTANI", label: "Tajikistani" },
  { value: "TANZANIAN", label: "Tanzanian" },
  {
    value: "FRENCH_SOUTHERN_TERRITORIES",
    label: "Territorios Franceses del Sur",
  },
  { value: "THAI", label: "Thai" },
  { value: "TIMORESE", label: "Timorese" },
  { value: "TOGOLESE", label: "Togolese" },
  { value: "TOKELAUAN", label: "Tokelauan" },
  { value: "TONGAN", label: "Tongan" },
  { value: "TRINIDADIAN_OR_TOBAGONIAN", label: "Trinidadian or tobagonian" },
  { value: "TUNISIAN", label: "Tunisian" },
  { value: "TURKISH", label: "Turkish" },
  { value: "TURKMEN", label: "Turkmen" },
  { value: "TURKS_AND_CAICOS_ISLANDER", label: "Turks and caicos islander" },
  { value: "UKRAINIAN", label: "Ucrania" },
  { value: "UGANDAN", label: "Ugandesas" },
  { value: "URUGUAYAN", label: "Uruguaya" },
  { value: "UZBEK", label: "Uzbeka" },
  { value: "VATICAN", label: "Vaticana" },
  { value: "VENEZUELAN", label: "Venezolana" },
  { value: "VINCENTIAN", label: "Vicenciana" },
  { value: "VIETNAMESE", label: "Vietnamita" },
  { value: "WALLISIAN_OR_FUTUNAN", label: "Wallisiano o Futunan" },
  { value: "YEMENI", label: "Yemenita" },
  { value: "I_KIRIBATI", label: "Yo kiribati" },
  { value: "ZAMBIANS", label: "Zambianas" },
  { value: "ZIMBABWEANS", label: "Zimbabuo" },
  { value: "IRANIAN", label: "iraní" },
  { value: "IRAQI", label: "iraquí" },
  { value: "ISRAELI", label: "israelí" },
  { value: "OMANI", label: "omani" },
  { value: "TUVALUAN", label: "tuvaluan" },
];

const Nationality = ({ ...rest }) => (
  <div className="p-r-20 p-l-20">
    <Input
      options={Nationalities}
      type={InputType.SELECT}
      placeholder="Nacionalidad"
      validate={(value) => value !== ""}
      {...rest}
    />
  </div>
);

export default Nationality;
